Hw 06
smartydan/ml2024 pull request #6
Opened 2024-04-17 18:09 UTC by smartydan

2024-04-20 11:36 UTC, svkov requested changes
Засчитываю только easy, пофикси в медиуме лемматизатор

2024-04-20 11:36 UTC, svkov commented on notebooks/06-homework.ipynb
> +    "import pymorphy3"
Вроде бы pymorphy работает только с русским и украинским языком

https://github.com/no-plagiarism/pymorphy3?tab=readme-ov-file#pymorphy3

2024-04-20 11:36 UTC, svkov commented on notebooks/06-homework.ipynb
> +    "    text = str(text)\n",
не хватает lower

2024-04-20 12:58 UTC, smartydan commented on notebooks/06-homework.ipynb
> +    "import pymorphy3"
поправил на другой

2024-04-27 12:17 UTC, svkov approved these changes
Зачтено

2024-04-27 18:10 UTC, merged