hw-8
smartydan/ml2024 pull request #8
Opened 2024-05-24 10:51 UTC by smartydan

2024-05-25 14:26 UTC, svkov requested changes
Нет примеров на все языки программирования в нужном формате

2024-05-26 23:08 UTC, smartydan commented
Хотелось бы иметь еще один раз, когда можно будет что-то исправить, а то файлики я просто забыл добавить

2024-05-28 15:55 UTC, svkov requested changes
1. Входные данные ограничены 4096 символами, в твоих примерах явно больше
2. Классифицировать надо не само сообщение из телеграма, а то, что лежит внутри текстового сниппета. А еще выборка, которая лежит в моем репо, нерепрезентативная, там 1000 случайных сообщений из случайных чатов, с кодом там очень мало примеров, на этом качество мерить неправильно.
3. А откуда взялась модель катбуста? Подозреваю, что из прошлой версии ноутбука, но я уже не помню, что там было
4. Я не помню в точности как ты обучался на гитхабе, но есть вероятность, что ты брал файлы, сплитил их на треин-тест, применял tf-idf или типа того и обучался. В таком случае ты переобучаешься, потому что в рамках одного репозитория код очень похожий. Сплитить нужно по репозиториям.

Все части решения есть, дособери данных и зачту easy+medium.

2024-06-01 16:19 UTC, smartydan commented
Да, я подгрузил модель, которую сохранил в предыдущей версии. Хорошо, данные дособираю

2024-06-01 16:26 UTC, svkov commented
> Да, я подгрузил модель, которую сохранил в предыдущей версии. Хорошо, данные дособираю

дедлайн прошел, больше не принимается

2024-06-02 18:59 UTC, closed without merging